#!/bin/bash
#=================================================
# Description: DIY script
# Lisence: MIT
# Author: eSirPlayground
# Youtube Channel: https://goo.gl/fvkdwm 
#=================================================
#1. Modify default IP
sed -i 's/192.168.1.1/192.168.6.1/g' openwrt/package/base-files/files/bin/config_generate

#2. Clear the login password
sed -i 's/$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.//g' openwrt/package/lean/default-settings/files/zzz-default-settings

#3. Replace with JerryKuKu’s Argon
#rm openwrt/package/lean/luci-theme-argon -rf

#4. Modify the system name
sed -i 's/OpenWrt /Fuwa@20230113 OpenWrt /g' openwrt/package/lean/default-settings/files/zzz-default-settings

#5. Customize ssh welcome message
cat /dev/null > openwrt/package/base-files/files/etc/banner

cat << EOF > openwrt/package/base-files/files/etc/banner
 ________ ___  ___  ___       __   ________     
|\  _____\\  \|\  \|\  \     |\  \|\   __  \    
\ \  \__/\ \  \\\  \ \  \    \ \  \ \  \|\  \   
 \ \   __\\ \  \\\  \ \  \  __\ \  \ \   __  \  
  \ \  \_| \ \  \\\  \ \  \|\__\_\  \ \  \ \  \ 
   \ \__\   \ \_______\ \____________\ \__\ \__\
    \|__|    \|_______|\|____________|\|__|\|__|
EOF
